concerts = [
	{
		day: "11",
		month: "07",
		year: 2024,
		city: "Seeshaupt",
		hall: "Seeresidenz Alte Post",
		link: "https://www.seeresidenz-alte-post.de/kultur/programm/november-2023/",
		visibility: "d-none",
		linkText: "Infos",
		cancelled: false
	},
	{
		day: "22",
		month: "06",
		year: 2024,
		city: "Kunstnacht Ausgburg",
		hall: "Moritzsaal | 21 & 22 Uhr",
		link: "",
		visibility: "d-none",
		linkText: "Infos",
		cancelled: false
	},
	{
		day: "16",
		month: "02",
		city: "Gräfelfing",
		year: 2024,
		hall: "Bürgerhaus",
		link: "https://www.muenchenticket.de/tickets/performances/e5usgx66gwjb/Trio-Merak",
		visibility: "",
		linkText: "Tickets",
		cancelled: false
	},
	{
		day: "11",
		month: "12",
		city: "Rotary München",
		year: 2023,
		hall: "Privatkonzert",
		link: "",
		visibility: "d-none",
		linkText: "",
		cancelled: false
	},
	{
		day: "28",
		month: "11",
		city: "Deutschlandstipendium Auftaktveranstaltung",
		year: 2023,
		hall: "Privatkonzert",
		link: "",
		visibility: "d-none",
		linkText: "",
		cancelled: false
	},
	{
		day: "17",
		month: "11",
		year: 2023,
		city: "Seeshaupt",
		hall: "Seeresidenz Alte Post",
		link: "https://www.seeresidenz-alte-post.de/kultur/programm/november-2023/",
		visibility: "",
		linkText: "Infos",
		cancelled: true
	},
	{
		day: "05",
		month: "07",
		year: 2023,
		city: "Tertianum Residenz München",
		hall: "Privatkonzert",
		link: "",
		visibility: "d-none",
		linkText: "",
		cancelled: false
	},
	{
		day: "02",
		month: "07",
		year: 2023,
		city: "Gemeinschaftliches Benefizkonzert für Musiker aus Kharkiv",
		hall: "Kirche St. Barbara - 18 Uhr | Infanteriestr. 15 | Spenden erwünscht",
		link: "",
		visibility: "d-none",
		linkText: "",
		cancelled: false
	},
	{
		day: "01",
		month: "07",
		year: 2023,
		city: "Abschlusskonzert",
		hall: "Reaktorhalle - 18 Uhr | Luisenstr. 37a | Eintritt frei!",
		link: "",
		visibility: "d-none",
		linkText: "",
		cancelled: false
	},
	{
		day: "18",
		month: "06",
		year: 2023,
		city: "Musik im Olympischen Dorf",
		hall: "Kath. Kirchenzentrum Frieden Christi - 19 Uhr | Eintritt frei!",
		link: "",
		visibility: "d-none",
		linkText: "",
		cancelled: false
	},
	{
		day: "16",
		month: "06",
		year: 2023,
		city: "Balkantage",
		hall: "Gasteig Saal X - 20 Uhr",
		link: "https://www.muenchenticket.de/tickets/performances/ep1dyct6pstg/Trio-MERAK",
		visibility: "",
		linkText: "Tickets",
		cancelled: false
	},
	{
		day: "15",
		month: "06",
		year: 2023,
		city: "Lesung der Autorin Ursula Kirchenmayer",
		hall: "Fraunhofer Theater - 20 Uhr",
		link: "https://www.fraunhofertheater.de/",
		visibility: "",
		linkText: "Infos",
		cancelled: false
	},
	{
		day: "07",
		month: "06",
		year: 2023,
		city: "Flower Power Festival",
		hall: "Reaktorhalle - 18 Uhr | Luisenstr. 37a | Eintritt frei!",
		link: "https://hmtm.de/veranstaltungen/flower-power-festival-sommerkonzert-der-schlagzeugklasse-muenchen/",
		visibility: "",
		linkText: "Infos",
		cancelled: false
	},
	{
		day: "20",
		month: "05",
		year: 2023,
		city: "Haar",
		hall: "Kleines Theater - 19 Uhr",
		link: "",
		visibility: "d-none",
		linkText: "",
		cancelled: false
	},
	{
		day: "06",
		month: "05",
		year: 2023,
		city: "Lange Nacht der Musik München",
		hall: "Großer Konzertsaal - 20 Uhr | Arcisstr. 12",
		link: "https://hmtm.de/veranstaltungen/lange-nacht-der-musik-eine-lange-kammermusik-nacht-2/",
		visibility: "",
		linkText: "Infos",
		cancelled: false
	},
	{
		day: "05",
		month: "05",
		year: 2023,
		city: "Chamberfest HMT München",
		hall: "Großer Konzertsaal - 19 Uhr | Arcisstr. 12",
		link: "https://hmtm.de/veranstaltungen/chamberfest-abschlusskonzert-alles-moeglich/",
		visibility: "",
		linkText: "Infos",
		cancelled: false
	},
	{
		day: "18",
		month: "04",
		year: 2023,
		city: "Gasteig HP8",
		hall: "Saal X - 18 Uhr Eintritt frei!",
		link: "",
		visibility: "d-none",
		linkText: "",
		cancelled: false
	},
	{
		day: "06",
		month: "12",
		year: 2022,
		city: "München",
		hall: "Reaktorhalle",
		link: "",
		visibility: "d-none",
		linkText: "",
		cancelled: false
	},
	{
		day: "17",
		month: "11",
		year: 2022,
		city: "München",
		hall: "Erlöserkirche Schwabing",
		link: "",
		visibility: "d-none",
		linkText: "",
		cancelled: false
	},
	{
		day: "13",
		month: "11",
		year: 2022,
		city: "München",
		hall: "Hochschule für Musik und Theater München",
		link: "",
		visibility: "d-none",
		linkText: "",
		cancelled: false
	},
	{
		day: "22",
		month: "10",
		year: 2022,
		city: "München",
		hall: "Kulturetage",
		link: "",
		visibility: "d-none",
		linkText: "",
		cancelled: false
	},
	{
		day: "28",
		month: "09",
		year: 2022,
		city: "München",
		hall: "Residenz",
		link: "",
		visibility: "d-none",
		linkText: "",
		cancelled: false
	},
	{
		day: "26",
		month: "06",
		year: 2022,
		city: "Balkantage München",
		hall: "",
		link: "",
		visibility: "d-none",
		linkText: "",
		cancelled: false
	},
	{
		day: "25",
		month: "06",
		year: 2022,
		city: "Augsburg",
		hall: "Schaetzlerpalais",
		link: "",
		visibility: "d-none",
		linkText: "",
		cancelled: false
	},
	{
		day: "02",
		month: "06",
		year: 2022,
		city: "Balkantage München",
		hall: "",
		link: "",
		visibility: "d-none",
		linkText: "",
		cancelled: false
	},
];
